export const Videos = [
    {id:1, url:require('./portfolioVideo1.mp4'), videoTitle:'Mariage Gitans Rebeux', videoDescription:'Dancefloor mixte musique urbaine !'},
    {id:2, url:require('./portfolioVideo2.mp4'), videoTitle:'Anniversaire 30 ans Carribean', videoDescription:'Ambiance sur le son de "Serani - No Games" et une excellente soirée pour un excellent anniversaire !'},
    {id:3, url:require('./portfolioVideo3.mp4'), videoTitle:'Anniversaire 21 ans', videoDescription:'Bonne ambiance sur le son "Waty by Night" de sexion d\'Assaut !'},
    {id:4, url:require('./portfolioVideo4.mp4'), videoTitle:'Place Vendome Partybus', videoDescription:'Petite pause à la place vendôme pendant la prestation !'},
    {id:5, url:require('./portfolioVideo5.mp4'), videoTitle:'Anniversaire 18 ans', videoDescription:'Une ambiance de folie sur Bande Organisée avec un groupe pleins de joies et de fêtes !'},
    {id:6, url:require('./portfolioVideo6.mp4'), videoTitle:'Anniversaire 18 ans Part2', videoDescription:'Micro en main, l\'ambiance de cette soirée sera inoubliable pour les invités comme pour moi !'},
    {id:7, url:require('./portfolioVideo7.mp4'), videoTitle:'Anniversaire 20 ans', videoDescription:'En place avec le collègue Nico, belle surprise pour la demoiselle du jour !'},
    {id:8, url:require('./portfolioVideo8.mp4'), videoTitle:'Tournée RFM', videoDescription:'Une ambiance de folie pendant la tournée RFM radio, avec des auditeurs prêts à faire la fête jusqu\'au bout de la nuit !'},
    {id:9, url:require('./portfolioVideo9.mp4'), videoTitle:'Anniversaire 21 ans', videoDescription:'qu\'est ce que j\'aime quand le public chante les chansons qui passent !'},
    {id:10, url:require('./portfolioVideo10.mp4'), videoTitle:'Soirée privée gitans', videoDescription:'Début de soirée pour un "Halloween Night" de folie !'},
    {id:11, url:require('./portfolioVideo11.mp4'), videoTitle:'Prestation Partybus Karaoké', videoDescription:'Nous savons tous que le karaoké, c\'est pour les gens qui ne savent pas chanter ... :p'},
    {id:12, url:require('./portfolioVideo12.mp4'), videoTitle:'Soirée d\'entreprise', videoDescription:'Un bon Ophélie Winter pour ces quarantenaires foux furieux de musique !'},
    {id:13, url:require('./portfolioVideo13.mp4'), videoTitle:'Soirée d\'entreprise', videoDescription:'Quand dieu te donne la foi, tu as cette force qui guide tes pas !'},
    {id:14, url:require('./portfolioVideo14.mp4'), videoTitle:'Reel Instagram Medley', videoDescription:'Les stories à la une dans un petit medley sur le son de Leto - "Tes Parents"'},
    {id:15, url:require('./portfolioVideo15.mp4'), videoTitle:'Anniversaire 20 ans', videoDescription:'La musique c\'est la puissance de ce monde ! Et ces jeunes le confirment !'},
    {id:16, url:require('./portfolioVideo16.mp4'), videoTitle:'Anniversaire 17 ans', videoDescription:'Il y a des morceaux comme ça qui sortent et qui font un carton ! ça ne s\'explique pas. Bonne ambiance sur celui ci !'},
    {id:17, url:require('./portfolioVideo17.mp4'), videoTitle:'Anniversaire Partybus', videoDescription:'Va te faire ... non quand même pas, ici on écoute de la musique !'},
    {id:18, url:require('./portfolioVideo18.mp4'), videoTitle:'Halloween Night', videoDescription:'Début de la soirée Halloween Night 2023'},
    {id:19, url:require('./portfolioVideo19.mp4'), videoTitle:'Pacha Club salle Sierra', videoDescription:'Matuidi Charo !!! ce son fait maintenant parti des classiques !!!'},
    {id:20, url:require('./portfolioVideo20.mp4'), videoTitle:'Soirée des Infirmiers/es de Chartres', videoDescription:'Petite soirée parisienne pour ces infirmiers qui viennent décompresser !'},
    {id:21, url:require('./portfolioVideo21.mp4'), videoTitle:'Chocolat vibes', videoDescription:'L\'Artiste et son chocolat coulent dans les veines de ces jeunes !'},
    {id:22, url:require('./portfolioVideo22.mp4'), videoTitle:'Anniversaire 17 ans', videoDescription:'Pourquoi ils aiment tous sauter comme ça !!! :p'},
    {id:23, url:require('./portfolioVideo23.mp4'), videoTitle:'Menelik Karaoké', videoDescription:'J\'adore quand dans un karaoké, il y a des musiques qui ont bercé mon enfance. Ménélik - "Bye Bye"'},
    {id:24, url:require('./portfolioVideo24.mp4'), videoTitle:'MAIS POURQUOI !', videoDescription:'Second degré bien sur mais qu\'est ce que vous massacrer cette musique en Karaoké !!! XD'},
    {id:25, url:require('./portfolioVideo25.mp4'), videoTitle:'Mariage Gitans Rebeux', videoDescription:'La danse des mariés, très joli moment pleins d\'amour'},
    {id:26, url:require('./portfolioVideo26.mp4'), videoTitle:'Anniversaire 25 ans', videoDescription:'Une bonne grosse ambiance arrive sur ce son de David Guetta !!!'},
    {id:27, url:require('./portfolioVideo27.mp4'), videoTitle:'Hey Ya', videoDescription:'Cette soirée de fin d\'année pour cette entreprise a été exceptionnel'},
    {id:28, url:require('./portfolioVideo28.mp4'), videoTitle:'Pacha Club', videoDescription:'Salle principale du Pacha Club'},
    {id:29, url:require('./portfolioVideo29.mp4'), videoTitle:'Karaoké Entreprise', videoDescription:'Les "Nèg Marron en karaoké, son culte des années 2000"'},
    {id:30, url:require('./portfolioVideo30.mp4'), videoTitle:'Reel Instagram', videoDescription:'Reel instagram des années 2023'},
    {id:31, url:require('./portfolioVideo31.mp4'), videoTitle:'Halloween Night', videoDescription:'On sort les masques pour Halloween ! Superbe soirée pleines de costumes en tout genre !'},
]